// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_uiu0UnKT9zAaY2IxqpRb2JMdNqXOeMA',
    appId: '1:938477802400:web:d1c637e56dadf100dd0ac5',
    messagingSenderId: '938477802400',
    projectId: 'blackcuack-studio',
    authDomain: 'blackcuack-studio.firebaseapp.com',
    storageBucket: 'blackcuack-studio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZQkAZnTkTBix3lGGbUTgg-96Gmiu-11g',
    appId: '1:938477802400:android:6a73e93bb2254e26dd0ac5',
    messagingSenderId: '938477802400',
    projectId: 'blackcuack-studio',
    storageBucket: 'blackcuack-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4QRGh1ZYXqdVIUp_DF-RCcufVR1C_jyE',
    appId: '1:938477802400:ios:1fd971f1c0dd55b6dd0ac5',
    messagingSenderId: '938477802400',
    projectId: 'blackcuack-studio',
    storageBucket: 'blackcuack-studio.firebasestorage.app',
    iosBundleId: 'com.animakids.blackcuackStudio',
  );

}